format = """
$directory\
[](fg:#A89984 bg:#504945)\
$git_branch\
$git_status\
[ ](fg:#504945)\
"""

# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[directory]
style = "fg:#1D2021 bg:#A89984"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#504945"
format = '[[ $symbol $branch ](bg:#504945)]($style)'

[git_status]
style = "bg:#504945"
format = '[[($all_status$ahead_behind )](bg:#504945)]($style)'

