format = """
$directory\
[](fg:#7aa2f7 bg:#292e42)\
$git_branch\
$git_status\
[ ](fg:#292e42)\
"""

# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[directory]
style = "fg:#292e42 bg:#7aa2f7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#7aa2f7 bg:#292e42"
format = '[[ $symbol $branch ](fg:#7aa2f7 bg:#292e42)]($style)'

[git_status]
style = "fg:#7aa2f7 bg:#292e42"
format = '[[($all_status$ahead_behind )](fg:#7aa2f7 bg:#292e42)]($style)'

